name: Check Dodgers Win
on:
  schedule:
    - cron: '0 16 * * *' # Runs at 9:00 AM PT daily
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requests
        run: pip install requests
      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
